image: elixir:1.9

services:
  - postgres:latest

variables:
  POSTGRES_DB: geo_racer_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force && mix local.rebar --force
  - mix do deps.get, compile
  - mix ecto.create
  - mix ecto.migrate

test:
  script:
  - mix test --trace

format:
  script:
    - mix format

credo:
  script:
    - mix credo