kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy
  namespace: default
subjects:
  - kind: ServiceAccount
    name: deploy
    namespace: default
roleRef:
  kind: Role
  name: deploy
  apiGroup: rbac.authorization.k8s.io